name:                storage-costs-evaluator
version:             0.1.0.0
github:              "ds-wizard/storage-costs-evaluator"
license:             MIT
author:              "Marek Suchánek"
maintainer:          "marek.suchanek@ds-wizard.org"
copyright:           "2019 Marek Suchánek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/storage-costs-evaluator#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- data-default
- lens
- scotty
- text
- wai
- wai-middleware-static

library:
  source-dirs: src
  default-extensions:
  - TemplateHaskell
  - OverloadedStrings
  - MultiParamTypeClasses
  - FunctionalDependencies
  - TypeSynonymInstances
  - FlexibleInstances
  - RecordWildCards

executables:
  storage-costs-evaluator:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - storage-costs-evaluator

tests:
  storage-costs-evaluator-test:
    main:                Spec.hs
    source-dirs:         test
    default-extensions:
    - OverloadedStrings
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - storage-costs-evaluator
    - hspec
    - hspec-wai
